### ISSUE TITLE
NGINX

### ISSUE THREAD

**Issue by Ryenum** [zhiyan114/SampleESP#1]
Hello, I'm sorry to bother you. I encountered some problems when configuring quic service of NGINX. My configuration is the same as that of the official website, but quic protocol still cannot be used when accessing the server, and h2 protocol is still used. Here is my compilation information:
root@learn:/usr/local/nginx/sbin# ./nginx -V
nginx version: nginx/1.16.1 (quiche-83d9168a)
built by gcc 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
built with OpenSSL 1.1.1 (compatible; BoringSSL) (running with BoringSSL)
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --build=quiche-83d9168a --with-http_v3_module --with-http_v2_module --with-quiche=/quiche --with-http_ssl_module --with-openssl=/quiche/quiche/deps/boringssl --add-module=/connect

Can you help me?

**Comment by zhiyan114** [comment]
https://github.com/cloudflare/quiche/issues/554#issuecomment-1837488572is an update to that. Also please don't open an issue on any random repository to ask a question that's not only unrelated to that repository, but also a question about an issue that the person posted 3 years ago..
